# Generated by Django 4.0.5 on 2022-07-04 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(db_column='orderID', primary_key=True, serialize=False)),
                ('customername', models.CharField(blank=True, db_column='customerName', max_length=200, null=True)),
                ('employeeid', models.IntegerField(db_column='employeeID')),
                ('time', models.CharField(blank=True, db_column='Time', max_length=200, null=True)),
                ('total', models.IntegerField(db_column='Total')),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('productimg', models.ImageField(db_column='IMG', max_length=255, upload_to='')),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('pricingid', models.AutoField(db_column='PricingID', primary_key=True, serialize=False)),
                ('base_price', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('in_active', models.CharField(max_length=1)),
                ('productid', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'pricing',
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('detailsid', models.AutoField(db_column='detailsID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('orderid', models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('productid', models.ForeignKey(db_column='productID', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'orderdetails',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discountid', models.AutoField(db_column='DiscountID', primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField()),
                ('from_field', models.DateTimeField(db_column='from')),
                ('until', models.DateTimeField()),
                ('productid', models.ForeignKey(db_column='productID', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'discount',
            },
        ),
    ]
