# Generated by Django 4.0.5 on 2022-08-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orderorderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimg', models.ImageField(db_column='IMG', max_length=255, upload_to='products/')),
            ],
            options={
                'db_table': 'img',
            },
        ),
    ]
