# Generated by Django 4.0.5 on 2022-08-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='productimg',
            field=models.ImageField(db_column='IMG', max_length=255, upload_to=''),
        ),
    ]
